# Config file for CI jobs on CircleCI (circleci.com).
version: 2.1

jobs:
  build-fedora:
    docker:
      - image: fedora
    steps:
      - run:
          name: Install Git
          command: dnf install -y git

      - checkout

      - run:
          name: Install dependencies
          command: |
            WX_EXTRA_PACKAGES=ccache ./build/tools/before_install.sh

            echo "PATH=/usr/lib64/ccache:$PATH" >> $BASH_ENV

      - run:
          name: Checkout required submodules
          command: |
            git submodule update --init 3rdparty/catch 3rdparty/nanosvg

      - restore_cache:
          name: Restore ccache
          keys:
            - ccache-v1-{{ arch }}-{{ .Branch }}
            - ccache-v1-{{ arch }}

      - run:
          name: Configure
          command: ./configure --disable-debug-info

      # Do _not_ use total CPU count for building, it is too high (36 logical
      # CPUs) and results in running out of memory, so limit ourselves to just
      # 2 CPUs we're supposed to be using in Docker Medium resource class.
      - run:
          name: Build
          command: |
            make -k -j2 CXXFLAGS='-Werror -Wno-error=cpp'

      - run:
          name: Show ccache statistics
          when: always
          command: ccache -vv -s

      - save_cache:
          name: Save ccache
          when: always
          key: ccache-v1-{{ arch }}-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - ~/.cache/ccache

workflows:
  build:
    jobs:
      - build-fedora
